"""create job revisions table

Revision ID: 29c03ef561ba
Revises: 081496f36c3b
Create Date: 2026-07-04 20:30:56.110875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29c03ef561ba'
down_revision: Union[str, None] = '081496f36c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('job_status', postgresql.ENUM('draft', 'open', 'closed', name='job_status', create_type=False), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_revisions_created_by'), 'job_revisions', ['created_by'], unique=False)
    op.create_index(op.f('ix_job_revisions_job_id'), 'job_revisions', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_revisions_job_id'), table_name='job_revisions')
    op.drop_index(op.f('ix_job_revisions_created_by'), table_name='job_revisions')
    op.drop_table('job_revisions')
    # ### end Alembic commands ###
