"""add_audit_log_table

Revision ID: 304a86f0e3ae
Revises: e1238a623de4
Create Date: 2026-05-31 05:28:45.565628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '304a86f0e3ae'
down_revision: Union[str, None] = 'e1238a623de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    # ### end Alembic commands ###

    # 1. Enable Row Level Security (RLS)
    op.execute("ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY")

    # 2. Add Multi-Tenant Isolation Policy
    op.execute(
        "CREATE POLICY audit_logs_tenant_isolation ON audit_logs "
        "FOR ALL "
        "USING ("
        "    company_id = NULLIF(current_setting('app.company_id', true), '')::uuid "
        "    OR current_setting('app.auth_mode', true) = 'true'"
        ") "
        "WITH CHECK ("
        "    company_id = NULLIF(current_setting('app.company_id', true), '')::uuid "
        "    OR current_setting('app.auth_mode', true) = 'true'"
        ")"
    )

    # 3. Add Immutability Protections (Trigger blocking UPDATE/DELETE)
    op.execute(
        """
        CREATE OR REPLACE FUNCTION block_audit_log_mutations()
        RETURNS TRIGGER AS $$
        BEGIN
            IF current_setting('app.bypass_audit_immutability', true) = 'true' THEN
                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                ELSE
                    RETURN NEW;
                END IF;
            END IF;
            RAISE EXCEPTION 'Audit logs are immutable append-only records.';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER check_audit_log_immutability
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION block_audit_log_mutations();
        """
    )


def downgrade() -> None:
    # Drop Immutability and RLS triggers/policies first
    op.execute("DROP TRIGGER IF EXISTS check_audit_log_immutability ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS block_audit_log_mutations")
    op.execute("DROP POLICY IF EXISTS audit_logs_tenant_isolation ON audit_logs")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
