"""add_sso_rollover_and_emergency

Revision ID: 43f9cec9398f
Revises: bb6390d5df47
Create Date: 2026-07-10 22:12:02.359223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43f9cec9398f'
down_revision: Union[str, None] = 'bb6390d5df47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_sso_settings', sa.Column('idp_x509_cert_next', sa.String(), nullable=True))
    op.add_column('company_sso_settings', sa.Column('idp_x509_cert_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('company_sso_settings', sa.Column('emergency_access_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_sso_settings', 'emergency_access_enabled')
    op.drop_column('company_sso_settings', 'idp_x509_cert_expiry')
    op.drop_column('company_sso_settings', 'idp_x509_cert_next')
    # ### end Alembic commands ###
