"""milestone_b3_schema

Revision ID: 4612fe6bcd5f
Revises: 29c03ef561ba
Create Date: 2026-07-05 02:36:49.047368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4612fe6bcd5f'
down_revision: Union[str, None] = '29c03ef561ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('candidate_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_tags_company_id'), 'candidate_tags', ['company_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_company_id'), 'roles', ['company_id'], unique=False)
    op.create_table('bulk_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('affected_application_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('previous_states', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_operations_company_id'), 'bulk_operations', ['company_id'], unique=False)
    op.create_index(op.f('ix_bulk_operations_recruiter_id'), 'bulk_operations', ['recruiter_id'], unique=False)
    op.create_table('candidate_tag_associations',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['candidate_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id', 'tag_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_company_id'), 'saved_searches', ['company_id'], unique=False)
    op.create_index(op.f('ix_saved_searches_recruiter_id'), 'saved_searches', ['recruiter_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('interview_kits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_definition_id', sa.UUID(), nullable=False),
    sa.Column('guide_markdown', sa.Text(), nullable=True),
    sa.Column('coding_challenge', sa.Text(), nullable=True),
    sa.Column('rubric_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('prohibited_questions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stage_definition_id'], ['stage_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_kits_stage_definition_id'), 'interview_kits', ['stage_definition_id'], unique=True)
    op.create_table('user_job_access',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'job_id')
    )
    op.create_table('application_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_events_event_type'), 'application_events', ['event_type'], unique=False)
    op.create_table('application_secondary_recruiters',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', 'user_id')
    )
    op.create_table('application_watchers',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', 'user_id')
    )
    op.add_column('applications', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_applications_owner_id'), 'applications', ['owner_id'], unique=False)
    op.create_foreign_key('fk_applications_owner_id', 'applications', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # op.drop_index(op.f('idx_candidate_embeddings_hnsw'), table_name='candidate_embeddings', postgresql_ops={'resume_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('candidate_notes', sa.Column('visibility', sa.String(length=50), server_default='everyone', nullable=False))
    op.alter_column('candidate_profiles', 'summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('candidate_resumes', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.alter_column('candidate_resumes', 'parsed_summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_candidate_resumes_file_hash'), 'candidate_resumes', ['file_hash'], unique=False)
    op.add_column('candidate_stage_sla_trackers', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidate_stage_sla_trackers', sa.Column('total_paused_seconds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('jobs', sa.Column('pipeline_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_jobs_pipeline_id'), 'jobs', ['pipeline_id'], unique=False)
    op.create_foreign_key('fk_jobs_pipeline_id', 'jobs', 'pipelines', ['pipeline_id'], ['id'], ondelete='SET NULL')
    op.add_column('scorecards', sa.Column('is_draft', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scorecards', 'is_draft')
    try:
        op.drop_constraint('jobs_pipeline_id_fkey', 'jobs', type_='foreignkey')
    except Exception:
        try:
            op.drop_constraint('fk_jobs_pipeline_id', 'jobs', type_='foreignkey')
        except Exception:
            pass
    op.drop_index(op.f('ix_jobs_pipeline_id'), table_name='jobs')
    op.drop_column('jobs', 'pipeline_id')
    op.drop_column('candidate_stage_sla_trackers', 'total_paused_seconds')
    op.drop_column('candidate_stage_sla_trackers', 'paused_at')
    op.drop_index(op.f('ix_candidate_resumes_file_hash'), table_name='candidate_resumes')
    op.alter_column('candidate_resumes', 'parsed_summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('candidate_resumes', 'file_hash')
    op.alter_column('candidate_profiles', 'summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('candidate_notes', 'visibility')
    # op.create_index(op.f('idx_candidate_embeddings_hnsw'), 'candidate_embeddings', ['resume_embedding'], unique=False, postgresql_ops={'resume_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    try:
        op.drop_constraint('applications_owner_id_fkey', 'applications', type_='foreignkey')
    except Exception:
        try:
            op.drop_constraint('fk_applications_owner_id', 'applications', type_='foreignkey')
        except Exception:
            pass
    op.drop_index(op.f('ix_applications_owner_id'), table_name='applications')
    op.drop_column('applications', 'owner_id')
    op.drop_table('application_watchers')
    op.drop_table('application_secondary_recruiters')
    op.drop_index(op.f('ix_application_events_event_type'), table_name='application_events')
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    op.drop_table('user_job_access')
    op.drop_index(op.f('ix_interview_kits_stage_definition_id'), table_name='interview_kits')
    op.drop_table('interview_kits')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_saved_searches_recruiter_id'), table_name='saved_searches')
    op.drop_index(op.f('ix_saved_searches_company_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('candidate_tag_associations')
    op.drop_index(op.f('ix_bulk_operations_recruiter_id'), table_name='bulk_operations')
    op.drop_index(op.f('ix_bulk_operations_company_id'), table_name='bulk_operations')
    op.drop_table('bulk_operations')
    op.drop_index(op.f('ix_roles_company_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_candidate_tags_company_id'), table_name='candidate_tags')
    op.drop_table('candidate_tags')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
