"""create quarantined_files table

Revision ID: 6ff16aa03210
Revises: 019_milestone11_phase3
Create Date: 2026-06-02 21:51:01.255681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '6ff16aa03210'
down_revision: Union[str, None] = '019_milestone11_phase3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('quarantined_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('quarantine_path', sa.String(length=512), nullable=False),
    sa.Column('is_safe', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarantined_files_company_id'), 'quarantined_files', ['company_id'], unique=False)
    
    # Enable Row-Level Security
    op.execute("ALTER TABLE quarantined_files ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE quarantined_files FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation_quarantined_files ON quarantined_files
        FOR ALL
        USING (
            company_id = NULLIF(current_setting('app.company_id', true), '')::uuid
            OR current_setting('app.auth_mode', true) = 'true'
        )
        WITH CHECK (
            company_id = NULLIF(current_setting('app.company_id', true), '')::uuid
            OR current_setting('app.auth_mode', true) = 'true'
        )
    """)
    op.create_index(op.f('ix_applications_current_stage_id'), 'applications', ['current_stage_id'], unique=False)
    op.alter_column('approval_steps', 'rejection_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('approval_templates', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('calendar_credentials', 'encrypted_access_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('calendar_credentials', 'encrypted_refresh_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('calendar_credentials', 'last_sync_error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_user_provider_calendar'), 'calendar_credentials', type_='unique')
    op.create_index(op.f('ix_calendar_credentials_company_id'), 'calendar_credentials', ['company_id'], unique=False)
    op.alter_column('candidate_embeddings', 'resume_embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=False)
    op.drop_index(op.f('idx_candidate_embeddings_standard'), table_name='candidate_embeddings', if_exists=True)
    op.drop_index(op.f('ix_candidate_stage_transitions_company_id_application_id'), table_name='candidate_stage_transitions')
    op.drop_index(op.f('ix_candidate_stage_transitions_to_status'), table_name='candidate_stage_transitions')
    op.create_index(op.f('ix_candidate_stage_transitions_application_id'), 'candidate_stage_transitions', ['application_id'], unique=False)
    op.create_index(op.f('ix_candidate_stage_transitions_company_id'), 'candidate_stage_transitions', ['company_id'], unique=False)
    op.drop_index(op.f('ix_committee_review_reviewers_review_id'), table_name='committee_review_reviewers')
    op.drop_constraint(op.f('uq_review_member_snapshot'), 'committee_review_reviewers', type_='unique')
    op.create_index(op.f('ix_committee_review_reviewers_committee_review_id'), 'committee_review_reviewers', ['committee_review_id'], unique=False)
    op.drop_constraint(op.f('uq_application_committee'), 'committee_reviews', type_='unique')
    op.create_index(op.f('ix_committee_reviews_company_id'), 'committee_reviews', ['company_id'], unique=False)
    op.alter_column('company_hris_integrations', 'credentials_encrypted',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_hris_integrations_company'), table_name='company_hris_integrations')
    op.create_index(op.f('ix_company_hris_integrations_company_id'), 'company_hris_integrations', ['company_id'], unique=False)
    op.alter_column('company_sso_settings', 'idp_x509_cert',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('company_sso_settings', 'oidc_client_secret',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_company_sso_settings'), 'company_sso_settings', type_='unique')
    op.drop_index(op.f('ix_company_sso_settings_company_id'), table_name='company_sso_settings')
    op.create_index(op.f('ix_company_sso_settings_company_id'), 'company_sso_settings', ['company_id'], unique=True)
    op.alter_column('dlq_records', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_dlq_records_company_status'), table_name='dlq_records')
    op.create_index(op.f('ix_dlq_records_company_id'), 'dlq_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_dlq_records_outbox_id'), 'dlq_records', ['outbox_id'], unique=False)
    op.alter_column('employee_sync_history', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_sync_history_company_employee'), table_name='employee_sync_history')
    op.drop_index(op.f('ix_sync_history_company_provider'), table_name='employee_sync_history')
    op.create_index(op.f('ix_employee_sync_history_company_id'), 'employee_sync_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_employee_sync_history_employee_id'), 'employee_sync_history', ['employee_id'], unique=False)
    op.alter_column('employees', 'sync_error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_employees_company_candidate'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_hris_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_supervisor'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_sync_status'), table_name='employees')
    op.create_index(op.f('ix_employees_candidate_id'), 'employees', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_employees_supervisor_id'), 'employees', ['supervisor_id'], unique=False)
    op.drop_constraint(op.f('uq_committee_member'), 'hiring_committee_members', type_='unique')
    op.drop_index(op.f('ix_field_mappings_company_provider'), table_name='hris_field_mappings')
    op.create_index(op.f('ix_hris_field_mappings_company_id'), 'hris_field_mappings', ['company_id'], unique=False)
    op.create_index(op.f('ix_interview_slots_company_id'), 'interview_slots', ['company_id'], unique=False)
    op.drop_constraint(op.f('uq_oauth_states_state_hash'), 'oauth_states', type_='unique')
    op.create_index(op.f('ix_oauth_states_company_id'), 'oauth_states', ['company_id'], unique=False)
    op.create_index(op.f('ix_oauth_states_user_id'), 'oauth_states', ['user_id'], unique=False)
    op.drop_constraint(op.f('offers_application_id_key'), 'offers', type_='unique')
    op.drop_index(op.f('ix_offers_application_id'), table_name='offers')
    op.create_index(op.f('ix_offers_application_id'), 'offers', ['application_id'], unique=True)
    op.drop_index(op.f('ix_onboarding_activity_employee'), table_name='onboarding_activity_log')
    op.drop_index(op.f('ix_onboarding_activity_event'), table_name='onboarding_activity_log')
    op.create_index(op.f('ix_onboarding_activity_log_company_id'), 'onboarding_activity_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_onboarding_activity_log_employee_id'), 'onboarding_activity_log', ['employee_id'], unique=False)
    op.create_index(op.f('ix_onboarding_activity_log_event_type'), 'onboarding_activity_log', ['event_type'], unique=False)
    op.drop_index(op.f('ix_doc_signatures_employee'), table_name='onboarding_document_signatures')
    op.create_index(op.f('ix_onboarding_document_signatures_company_id'), 'onboarding_document_signatures', ['company_id'], unique=False)
    op.create_index(op.f('ix_onboarding_document_signatures_document_id'), 'onboarding_document_signatures', ['document_id'], unique=False)
    op.create_index(op.f('ix_onboarding_document_signatures_employee_id'), 'onboarding_document_signatures', ['employee_id'], unique=False)
    op.alter_column('onboarding_documents', 'storage_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_onboarding_documents_company_task'), table_name='onboarding_documents')
    op.create_index(op.f('ix_onboarding_documents_company_id'), 'onboarding_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_onboarding_documents_task_id'), 'onboarding_documents', ['task_id'], unique=False)
    op.alter_column('onboarding_event_outbox', 'last_error',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_event_outbox_company_status'), table_name='onboarding_event_outbox')
    op.create_index(op.f('ix_onboarding_event_outbox_company_id'), 'onboarding_event_outbox', ['company_id'], unique=False)
    op.drop_index(op.f('ix_portal_tokens_employee'), table_name='onboarding_portal_tokens')
    op.drop_index(op.f('ix_portal_tokens_hash'), table_name='onboarding_portal_tokens')
    op.drop_constraint(op.f('onboarding_portal_tokens_token_hash_key'), 'onboarding_portal_tokens', type_='unique')
    op.create_index(op.f('ix_onboarding_portal_tokens_company_id'), 'onboarding_portal_tokens', ['company_id'], unique=False)
    op.create_index(op.f('ix_onboarding_portal_tokens_employee_id'), 'onboarding_portal_tokens', ['employee_id'], unique=False)
    op.create_index(op.f('ix_onboarding_portal_tokens_token_hash'), 'onboarding_portal_tokens', ['token_hash'], unique=True)
    op.drop_index(op.f('ix_task_escalations_unresolved'), table_name='onboarding_task_escalations', postgresql_where='(resolved_at IS NULL)')
    op.create_index(op.f('ix_onboarding_task_escalations_company_id'), 'onboarding_task_escalations', ['company_id'], unique=False)
    op.create_index(op.f('ix_onboarding_task_escalations_escalated_to_id'), 'onboarding_task_escalations', ['escalated_to_id'], unique=False)
    op.create_index(op.f('ix_onboarding_task_escalations_task_id'), 'onboarding_task_escalations', ['task_id'], unique=False)
    op.drop_index(op.f('ix_task_reminders_status_time'), table_name='onboarding_task_reminders')
    op.create_index(op.f('ix_onboarding_task_reminders_company_id'), 'onboarding_task_reminders', ['company_id'], unique=False)
    op.create_index(op.f('ix_onboarding_task_reminders_task_id'), 'onboarding_task_reminders', ['task_id'], unique=False)
    op.alter_column('onboarding_tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_onboarding_tasks_company_workflow'), table_name='onboarding_tasks')
    op.create_index(op.f('ix_onboarding_tasks_company_id'), 'onboarding_tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_onboarding_tasks_workflow_id'), 'onboarding_tasks', ['workflow_id'], unique=False)
    op.alter_column('onboarding_template_tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('onboarding_templates', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_onboarding_workflows_company_employee'), table_name='onboarding_workflows')
    op.drop_constraint(op.f('onboarding_workflows_employee_id_key'), 'onboarding_workflows', type_='unique')
    op.create_index(op.f('ix_onboarding_workflows_company_id'), 'onboarding_workflows', ['company_id'], unique=False)
    op.create_index(op.f('ix_onboarding_workflows_employee_id'), 'onboarding_workflows', ['employee_id'], unique=True)
    op.alter_column('pipeline_templates', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('pipelines', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_interview_scheduling_link'), 'scheduling_links', type_='unique')
    op.drop_constraint(op.f('uq_scheduling_links_token_hash'), 'scheduling_links', type_='unique')
    op.create_index(op.f('ix_scheduling_links_company_id'), 'scheduling_links', ['company_id'], unique=False)
    op.create_index(op.f('ix_scheduling_links_interview_id'), 'scheduling_links', ['interview_id'], unique=True)
    op.drop_constraint(op.f('uq_template_skill'), 'scorecard_template_skills', type_='unique')
    op.create_index(op.f('ix_scorecards_committee_review_id'), 'scorecards', ['committee_review_id'], unique=False)
    op.drop_index(op.f('ix_sync_metrics_company_metric'), table_name='sync_metrics')
    op.create_index(op.f('ix_sync_metrics_company_id'), 'sync_metrics', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_metrics_company_id'), table_name='sync_metrics')
    op.create_index(op.f('ix_sync_metrics_company_metric'), 'sync_metrics', ['company_id', 'metric_name', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_scorecards_committee_review_id'), table_name='scorecards')
    op.create_unique_constraint(op.f('uq_template_skill'), 'scorecard_template_skills', ['scorecard_template_id', 'skill_key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_scheduling_links_interview_id'), table_name='scheduling_links')
    op.drop_index(op.f('ix_scheduling_links_company_id'), table_name='scheduling_links')
    op.create_unique_constraint(op.f('uq_scheduling_links_token_hash'), 'scheduling_links', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_interview_scheduling_link'), 'scheduling_links', ['interview_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('pipelines', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('pipeline_templates', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_onboarding_workflows_employee_id'), table_name='onboarding_workflows')
    op.drop_index(op.f('ix_onboarding_workflows_company_id'), table_name='onboarding_workflows')
    op.create_unique_constraint(op.f('onboarding_workflows_employee_id_key'), 'onboarding_workflows', ['employee_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_onboarding_workflows_company_employee'), 'onboarding_workflows', ['company_id', 'employee_id', 'status'], unique=False)
    op.alter_column('onboarding_templates', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('onboarding_template_tasks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_onboarding_tasks_workflow_id'), table_name='onboarding_tasks')
    op.drop_index(op.f('ix_onboarding_tasks_company_id'), table_name='onboarding_tasks')
    op.create_index(op.f('ix_onboarding_tasks_company_workflow'), 'onboarding_tasks', ['company_id', 'workflow_id', 'status', 'assigned_to_role'], unique=False)
    op.alter_column('onboarding_tasks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_onboarding_task_reminders_task_id'), table_name='onboarding_task_reminders')
    op.drop_index(op.f('ix_onboarding_task_reminders_company_id'), table_name='onboarding_task_reminders')
    op.create_index(op.f('ix_task_reminders_status_time'), 'onboarding_task_reminders', ['company_id', 'status', 'scheduled_at'], unique=False)
    op.drop_index(op.f('ix_onboarding_task_escalations_task_id'), table_name='onboarding_task_escalations')
    op.drop_index(op.f('ix_onboarding_task_escalations_escalated_to_id'), table_name='onboarding_task_escalations')
    op.drop_index(op.f('ix_onboarding_task_escalations_company_id'), table_name='onboarding_task_escalations')
    op.create_index(op.f('ix_task_escalations_unresolved'), 'onboarding_task_escalations', ['company_id', 'task_id'], unique=False, postgresql_where='(resolved_at IS NULL)')
    op.drop_index(op.f('ix_onboarding_portal_tokens_token_hash'), table_name='onboarding_portal_tokens')
    op.drop_index(op.f('ix_onboarding_portal_tokens_employee_id'), table_name='onboarding_portal_tokens')
    op.drop_index(op.f('ix_onboarding_portal_tokens_company_id'), table_name='onboarding_portal_tokens')
    op.create_unique_constraint(op.f('onboarding_portal_tokens_token_hash_key'), 'onboarding_portal_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_portal_tokens_hash'), 'onboarding_portal_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_portal_tokens_employee'), 'onboarding_portal_tokens', ['company_id', 'employee_id'], unique=False)
    op.drop_index(op.f('ix_onboarding_event_outbox_company_id'), table_name='onboarding_event_outbox')
    op.create_index(op.f('ix_event_outbox_company_status'), 'onboarding_event_outbox', ['company_id', 'status', 'event_type'], unique=False)
    op.alter_column('onboarding_event_outbox', 'last_error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_onboarding_documents_task_id'), table_name='onboarding_documents')
    op.drop_index(op.f('ix_onboarding_documents_company_id'), table_name='onboarding_documents')
    op.create_index(op.f('ix_onboarding_documents_company_task'), 'onboarding_documents', ['company_id', 'task_id', 'signature_status'], unique=False)
    op.alter_column('onboarding_documents', 'storage_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_onboarding_document_signatures_employee_id'), table_name='onboarding_document_signatures')
    op.drop_index(op.f('ix_onboarding_document_signatures_document_id'), table_name='onboarding_document_signatures')
    op.drop_index(op.f('ix_onboarding_document_signatures_company_id'), table_name='onboarding_document_signatures')
    op.create_index(op.f('ix_doc_signatures_employee'), 'onboarding_document_signatures', ['company_id', 'employee_id'], unique=False)
    op.drop_index(op.f('ix_onboarding_activity_log_event_type'), table_name='onboarding_activity_log')
    op.drop_index(op.f('ix_onboarding_activity_log_employee_id'), table_name='onboarding_activity_log')
    op.drop_index(op.f('ix_onboarding_activity_log_company_id'), table_name='onboarding_activity_log')
    op.create_index(op.f('ix_onboarding_activity_event'), 'onboarding_activity_log', ['company_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_onboarding_activity_employee'), 'onboarding_activity_log', ['company_id', 'employee_id'], unique=False)
    op.drop_index(op.f('ix_offers_application_id'), table_name='offers')
    op.create_index(op.f('ix_offers_application_id'), 'offers', ['application_id'], unique=False)
    op.create_unique_constraint(op.f('offers_application_id_key'), 'offers', ['application_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_oauth_states_user_id'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_company_id'), table_name='oauth_states')
    op.create_unique_constraint(op.f('uq_oauth_states_state_hash'), 'oauth_states', ['state_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_interview_slots_company_id'), table_name='interview_slots')
    op.drop_index(op.f('ix_hris_field_mappings_company_id'), table_name='hris_field_mappings')
    op.create_index(op.f('ix_field_mappings_company_provider'), 'hris_field_mappings', ['company_id', 'provider'], unique=False)
    op.create_unique_constraint(op.f('uq_committee_member'), 'hiring_committee_members', ['hiring_committee_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_employees_supervisor_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_candidate_id'), table_name='employees')
    op.create_index(op.f('ix_employees_company_sync_status'), 'employees', ['company_id', 'sync_status'], unique=False)
    op.create_index(op.f('ix_employees_company_supervisor'), 'employees', ['company_id', 'supervisor_id'], unique=False)
    op.create_index(op.f('ix_employees_company_hris_id'), 'employees', ['company_id', 'hris_id'], unique=False)
    op.create_index(op.f('ix_employees_company_email'), 'employees', ['company_id', 'email'], unique=False)
    op.create_index(op.f('ix_employees_company_candidate'), 'employees', ['company_id', 'candidate_id'], unique=False)
    op.alter_column('employees', 'sync_error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_employee_sync_history_employee_id'), table_name='employee_sync_history')
    op.drop_index(op.f('ix_employee_sync_history_company_id'), table_name='employee_sync_history')
    op.create_index(op.f('ix_sync_history_company_provider'), 'employee_sync_history', ['company_id', 'provider'], unique=False)
    op.create_index(op.f('ix_sync_history_company_employee'), 'employee_sync_history', ['company_id', 'employee_id'], unique=False)
    op.alter_column('employee_sync_history', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_dlq_records_outbox_id'), table_name='dlq_records')
    op.drop_index(op.f('ix_dlq_records_company_id'), table_name='dlq_records')
    op.create_index(op.f('ix_dlq_records_company_status'), 'dlq_records', ['company_id', 'status'], unique=False)
    op.alter_column('dlq_records', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_company_sso_settings_company_id'), table_name='company_sso_settings')
    op.create_index(op.f('ix_company_sso_settings_company_id'), 'company_sso_settings', ['company_id'], unique=False)
    op.create_unique_constraint(op.f('uq_company_sso_settings'), 'company_sso_settings', ['company_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('company_sso_settings', 'oidc_client_secret',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('company_sso_settings', 'idp_x509_cert',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_company_hris_integrations_company_id'), table_name='company_hris_integrations')
    op.create_index(op.f('ix_hris_integrations_company'), 'company_hris_integrations', ['company_id', 'provider'], unique=False)
    op.alter_column('company_hris_integrations', 'credentials_encrypted',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_committee_reviews_company_id'), table_name='committee_reviews')
    op.create_unique_constraint(op.f('uq_application_committee'), 'committee_reviews', ['application_id', 'hiring_committee_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_committee_review_reviewers_committee_review_id'), table_name='committee_review_reviewers')
    op.create_unique_constraint(op.f('uq_review_member_snapshot'), 'committee_review_reviewers', ['committee_review_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_committee_review_reviewers_review_id'), 'committee_review_reviewers', ['committee_review_id'], unique=False)
    op.drop_index(op.f('ix_candidate_stage_transitions_company_id'), table_name='candidate_stage_transitions')
    op.drop_index(op.f('ix_candidate_stage_transitions_application_id'), table_name='candidate_stage_transitions')
    op.create_index(op.f('ix_candidate_stage_transitions_to_status'), 'candidate_stage_transitions', ['to_status'], unique=False)
    op.create_index(op.f('ix_candidate_stage_transitions_company_id_application_id'), 'candidate_stage_transitions', ['company_id', 'application_id'], unique=False)
    op.create_index(op.f('idx_candidate_embeddings_standard'), 'candidate_embeddings', ['candidate_id', 'chunk_index'], unique=False)
    op.alter_column('candidate_embeddings', 'resume_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=False)
    op.drop_index(op.f('ix_calendar_credentials_company_id'), table_name='calendar_credentials')
    op.create_unique_constraint(op.f('uq_user_provider_calendar'), 'calendar_credentials', ['company_id', 'user_id', 'provider', 'account_email'], postgresql_nulls_not_distinct=False)
    op.alter_column('calendar_credentials', 'last_sync_error',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('calendar_credentials', 'encrypted_refresh_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('calendar_credentials', 'encrypted_access_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('approval_templates', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('approval_steps', 'rejection_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_applications_current_stage_id'), table_name='applications')
    op.execute("DROP POLICY IF EXISTS tenant_isolation_quarantined_files ON quarantined_files")
    op.drop_index(op.f('ix_quarantined_files_company_id'), table_name='quarantined_files')
    op.drop_table('quarantined_files')
    # ### end Alembic commands ###
