"""add_ai_recruiter_agent_platform

Revision ID: 849c8fab264b
Revises: phase_c3_crm
Create Date: 2026-07-10 21:30:19.885898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '849c8fab264b'
down_revision: Union[str, None] = 'phase_c3_crm'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_planner_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('saved_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_planner_templates_company_id'), 'agent_planner_templates', ['company_id'], unique=False)
    
    op.create_table('ai_copilot_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('tools_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('planning_time_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('approval_delay_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('plan_complexity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_copilot_call_logs_company_id'), 'ai_copilot_call_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_ai_copilot_call_logs_recruiter_id'), 'ai_copilot_call_logs', ['recruiter_id'], unique=False)
    
    op.create_table('recruiter_chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('session_name', sa.Text(), nullable=False),
    sa.Column('current_job_id', sa.UUID(), nullable=True),
    sa.Column('current_pool_id', sa.UUID(), nullable=True),
    sa.Column('current_filters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('selected_candidate_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('context_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('expires_after', sa.Integer(), server_default='86400', nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_pool_id'], ['talent_pools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_chat_sessions_company_id'), 'recruiter_chat_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_recruiter_chat_sessions_recruiter_id'), 'recruiter_chat_sessions', ['recruiter_id'], unique=False)
    
    op.create_table('recruiter_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('execution_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan_confidence', sa.Float(), nullable=True),
    sa.Column('plan_confidence_reason', sa.Text(), nullable=True),
    sa.Column('plan_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('permission_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['recruiter_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_chat_messages_session_id'), 'recruiter_chat_messages', ['session_id'], unique=False)

    # Enable Row-Level Security (RLS) policies
    op.execute("ALTER TABLE agent_planner_templates ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE ai_copilot_call_logs ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE recruiter_chat_sessions ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE recruiter_chat_messages ENABLE ROW LEVEL SECURITY;")

    op.execute(
        "CREATE POLICY agent_planner_templates_tenant_isolation ON agent_planner_templates "
        "FOR ALL USING (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);"
    )
    op.execute(
        "CREATE POLICY ai_copilot_call_logs_tenant_isolation ON ai_copilot_call_logs "
        "FOR ALL USING (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);"
    )
    op.execute(
        "CREATE POLICY recruiter_chat_sessions_tenant_isolation ON recruiter_chat_sessions "
        "FOR ALL USING (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);"
    )
    op.execute(
        "CREATE POLICY recruiter_chat_messages_tenant_isolation ON recruiter_chat_messages "
        "FOR ALL USING (EXISTS (SELECT 1 FROM recruiter_chat_sessions WHERE recruiter_chat_sessions.id = session_id "
        "AND recruiter_chat_sessions.company_id = NULLIF(current_setting('app.company_id', true), '')::uuid));"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruiter_chat_messages')
    op.drop_table('recruiter_chat_sessions')
    op.drop_table('ai_copilot_call_logs')
    op.drop_table('agent_planner_templates')
    # ### end Alembic commands ###
