"""milestone_12_schema

Revision ID: fae88da6f6a4
Revises: 6ff16aa03210
Create Date: 2026-06-02 22:10:39.747805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fae88da6f6a4'
down_revision: Union[str, None] = '6ff16aa03210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending_verification', 'verified_recruiter', 'verified_company', 'suspended', name='verification_state').create(op.get_bind())
    sa.Enum('none', 'trusted_employer', name='trust_level').create(op.get_bind())
    op.create_table('company_trust_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('hiring_history_count', sa.Integer(), nullable=False),
    sa.Column('interview_completion_rate', sa.Float(), nullable=False),
    sa.Column('candidate_complaint_rate', sa.Float(), nullable=False),
    sa.Column('offer_acceptance_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_trust_metrics_company_id'), 'company_trust_metrics', ['company_id'], unique=True)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('profile_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=True)
    op.create_table('verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_user_id'), 'verification_tokens', ['user_id'], unique=False)
    op.create_table('application_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('resume_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_snapshots_application_id'), 'application_snapshots', ['application_id'], unique=True)
    op.add_column('companies', sa.Column('verification_state', sa.Enum('pending_verification', 'verified_recruiter', 'verified_company', 'suspended', name='verification_state'), nullable=False))
    op.add_column('companies', sa.Column('trust_level', sa.Enum('none', 'trusted_employer', name='trust_level'), nullable=False))
    op.add_column('companies', sa.Column('domain_verified', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('website_verified', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('identity_verified', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('is_verified_recruiter', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('is_verified_company', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('is_trusted_employer', sa.Boolean(), nullable=False))
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('companies', 'is_trusted_employer')
    op.drop_column('companies', 'is_verified_company')
    op.drop_column('companies', 'is_verified_recruiter')
    op.drop_column('companies', 'identity_verified')
    op.drop_column('companies', 'website_verified')
    op.drop_column('companies', 'domain_verified')
    op.drop_column('companies', 'trust_level')
    op.drop_column('companies', 'verification_state')
    op.drop_index(op.f('ix_application_snapshots_application_id'), table_name='application_snapshots')
    op.drop_table('application_snapshots')
    op.drop_index(op.f('ix_verification_tokens_user_id'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_company_trust_metrics_company_id'), table_name='company_trust_metrics')
    op.drop_table('company_trust_metrics')
    sa.Enum('pending_verification', 'verified_recruiter', 'verified_company', 'suspended', name='verification_state').drop(op.get_bind())
    sa.Enum('none', 'trusted_employer', name='trust_level').drop(op.get_bind())
    # ### end Alembic commands ###
